	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.include "sound/drum_sample_data.inc"

	.include "sound/keysplit_sample_data.inc"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

	.include "sound/cry_sample_data.inc"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.include "sound/phoneme_sample_data.inc"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
