	.align 2
DirectSoundWaveData_Phoneme_1::
	.incbin "sound/direct_sound_samples/phonemes/01.bin"

	.align 2
DirectSoundWaveData_Phoneme_2::
	.incbin "sound/direct_sound_samples/phonemes/02.bin"

	.align 2
DirectSoundWaveData_Phoneme_3::
	.incbin "sound/direct_sound_samples/phonemes/03.bin"

	.align 2
DirectSoundWaveData_Phoneme_4::
	.incbin "sound/direct_sound_samples/phonemes/04.bin"

	.align 2
DirectSoundWaveData_Phoneme_5::
	.incbin "sound/direct_sound_samples/phonemes/05.bin"

	.align 2
DirectSoundWaveData_Phoneme_6::
	.incbin "sound/direct_sound_samples/phonemes/06.bin"

	.align 2
DirectSoundWaveData_Phoneme_7::
	.incbin "sound/direct_sound_samples/phonemes/07.bin"

	.align 2
DirectSoundWaveData_Phoneme_8::
	.incbin "sound/direct_sound_samples/phonemes/08.bin"

	.align 2
DirectSoundWaveData_Phoneme_9::
	.incbin "sound/direct_sound_samples/phonemes/09.bin"

	.align 2
DirectSoundWaveData_Phoneme_10::
	.incbin "sound/direct_sound_samples/phonemes/10.bin"

	.align 2
DirectSoundWaveData_Phoneme_11::
	.incbin "sound/direct_sound_samples/phonemes/11.bin"

	.align 2
DirectSoundWaveData_Phoneme_12::
	.incbin "sound/direct_sound_samples/phonemes/12.bin"

	.align 2
DirectSoundWaveData_Phoneme_13::
	.incbin "sound/direct_sound_samples/phonemes/13.bin"

	.align 2
DirectSoundWaveData_Phoneme_14::
	.incbin "sound/direct_sound_samples/phonemes/14.bin"

	.align 2
DirectSoundWaveData_Phoneme_15::
	.incbin "sound/direct_sound_samples/phonemes/15.bin"

	.align 2
DirectSoundWaveData_Phoneme_16::
	.incbin "sound/direct_sound_samples/phonemes/16.bin"

	.align 2
DirectSoundWaveData_Phoneme_17::
	.incbin "sound/direct_sound_samples/phonemes/17.bin"

	.align 2
DirectSoundWaveData_Phoneme_18::
	.incbin "sound/direct_sound_samples/phonemes/18.bin"

	.align 2
DirectSoundWaveData_Phoneme_19::
	.incbin "sound/direct_sound_samples/phonemes/19.bin"

	.align 2
DirectSoundWaveData_Phoneme_20::
	.incbin "sound/direct_sound_samples/phonemes/20.bin"

	.align 2
DirectSoundWaveData_Phoneme_21::
	.incbin "sound/direct_sound_samples/phonemes/21.bin"

	.align 2
DirectSoundWaveData_Phoneme_22::
	.incbin "sound/direct_sound_samples/phonemes/22.bin"

	.align 2
DirectSoundWaveData_Phoneme_23::
	.incbin "sound/direct_sound_samples/phonemes/23.bin"

	.align 2
DirectSoundWaveData_Phoneme_24::
	.incbin "sound/direct_sound_samples/phonemes/24.bin"

	.align 2
DirectSoundWaveData_Phoneme_25::
	.incbin "sound/direct_sound_samples/phonemes/25.bin"

	.align 2
DirectSoundWaveData_Phoneme_26::
	.incbin "sound/direct_sound_samples/phonemes/26.bin"

	.align 2
DirectSoundWaveData_Phoneme_27::
	.incbin "sound/direct_sound_samples/phonemes/27.bin"

	.align 2
DirectSoundWaveData_Phoneme_28::
	.incbin "sound/direct_sound_samples/phonemes/28.bin"

	.align 2
DirectSoundWaveData_Phoneme_29::
	.incbin "sound/direct_sound_samples/phonemes/29.bin"

	.align 2
DirectSoundWaveData_Phoneme_30::
	.incbin "sound/direct_sound_samples/phonemes/30.bin"

	.align 2
DirectSoundWaveData_Phoneme_31::
	.incbin "sound/direct_sound_samples/phonemes/31.bin"

	.align 2
DirectSoundWaveData_Phoneme_32::
	.incbin "sound/direct_sound_samples/phonemes/32.bin"

	.align 2
DirectSoundWaveData_Phoneme_33::
	.incbin "sound/direct_sound_samples/phonemes/33.bin"

	.align 2
DirectSoundWaveData_Phoneme_34::
	.incbin "sound/direct_sound_samples/phonemes/34.bin"

	.align 2
DirectSoundWaveData_Phoneme_35::
	.incbin "sound/direct_sound_samples/phonemes/35.bin"

	.align 2
DirectSoundWaveData_Phoneme_36::
	.incbin "sound/direct_sound_samples/phonemes/36.bin"

	.align 2
DirectSoundWaveData_Phoneme_37::
	.incbin "sound/direct_sound_samples/phonemes/37.bin"

	.align 2
DirectSoundWaveData_Phoneme_38::
	.incbin "sound/direct_sound_samples/phonemes/38.bin"

	.align 2
DirectSoundWaveData_Phoneme_39::
	.incbin "sound/direct_sound_samples/phonemes/39.bin"

	.align 2
DirectSoundWaveData_Phoneme_40::
	.incbin "sound/direct_sound_samples/phonemes/40.bin"

	.align 2
DirectSoundWaveData_Phoneme_41::
	.incbin "sound/direct_sound_samples/phonemes/41.bin"

	.align 2
DirectSoundWaveData_Phoneme_42::
	.incbin "sound/direct_sound_samples/phonemes/42.bin"

	.align 2
DirectSoundWaveData_Phoneme_43::
	.incbin "sound/direct_sound_samples/phonemes/43.bin"

	.align 2
DirectSoundWaveData_Phoneme_44::
	.incbin "sound/direct_sound_samples/phonemes/44.bin"

	.align 2
DirectSoundWaveData_Phoneme_45::
	.incbin "sound/direct_sound_samples/phonemes/45.bin"

	.align 2
DirectSoundWaveData_Phoneme_46::
	.incbin "sound/direct_sound_samples/phonemes/46.bin"

	.align 2
DirectSoundWaveData_Phoneme_47::
	.incbin "sound/direct_sound_samples/phonemes/47.bin"

	.align 2
DirectSoundWaveData_Phoneme_48::
	.incbin "sound/direct_sound_samples/phonemes/48.bin"

	.align 2
DirectSoundWaveData_Phoneme_49::
	.incbin "sound/direct_sound_samples/phonemes/49.bin"

	.align 2
DirectSoundWaveData_Phoneme_50::
	.incbin "sound/direct_sound_samples/phonemes/50.bin"

	.align 2
DirectSoundWaveData_Phoneme_51::
	.incbin "sound/direct_sound_samples/phonemes/51.bin"
