#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define EVENT_OBJ_GFX_BRENDAN_NORMAL               0
#define EVENT_OBJ_GFX_BRENDAN_MACH_BIKE            1
#define EVENT_OBJ_GFX_BRENDAN_SURFING              2
#define EVENT_OBJ_GFX_BRENDAN_FIELD_MOVE           3
#define EVENT_OBJ_GFX_NINJA_BOY                    4
#define EVENT_OBJ_GFX_TWIN                         5
#define EVENT_OBJ_GFX_BOY_1                        6
#define EVENT_OBJ_GFX_GIRL_1                       7
#define EVENT_OBJ_GFX_BOY_2                        8
#define EVENT_OBJ_GFX_GIRL_2                       9
#define EVENT_OBJ_GFX_LITTLE_BOY                  10
#define EVENT_OBJ_GFX_LITTLE_GIRL                 11
#define EVENT_OBJ_GFX_BOY_3                       12
#define EVENT_OBJ_GFX_GIRL_3                      13
#define EVENT_OBJ_GFX_RICH_BOY                    14
#define EVENT_OBJ_GFX_WOMAN_1                     15
#define EVENT_OBJ_GFX_FAT_MAN                     16
#define EVENT_OBJ_GFX_POKEFAN_F                   17
#define EVENT_OBJ_GFX_MAN_1                       18
#define EVENT_OBJ_GFX_WOMAN_2                     19
#define EVENT_OBJ_GFX_EXPERT_M                    20
#define EVENT_OBJ_GFX_EXPERT_F                    21
#define EVENT_OBJ_GFX_MAN_2                       22
#define EVENT_OBJ_GFX_WOMAN_3                     23
#define EVENT_OBJ_GFX_POKEFAN_M                   24
#define EVENT_OBJ_GFX_WOMAN_4                     25
#define EVENT_OBJ_GFX_COOK                        26
#define EVENT_OBJ_GFX_LINK_RECEPTIONIST           27
#define EVENT_OBJ_GFX_OLD_MAN                     28
#define EVENT_OBJ_GFX_OLD_WOMAN                   29
#define EVENT_OBJ_GFX_CAMPER                      30
#define EVENT_OBJ_GFX_PICNICKER                   31
#define EVENT_OBJ_GFX_MAN_3                       32
#define EVENT_OBJ_GFX_WOMAN_5                     33
#define EVENT_OBJ_GFX_YOUNGSTER                   34
#define EVENT_OBJ_GFX_BUG_CATCHER                 35
#define EVENT_OBJ_GFX_PSYCHIC_M                   36
#define EVENT_OBJ_GFX_SCHOOL_KID_M                37
#define EVENT_OBJ_GFX_MANIAC                      38
#define EVENT_OBJ_GFX_HEX_MANIAC                  39
#define EVENT_OBJ_GFX_RAYQUAZA_1                  40
#define EVENT_OBJ_GFX_SWIMMER_M                   41
#define EVENT_OBJ_GFX_SWIMMER_F                   42
#define EVENT_OBJ_GFX_BLACK_BELT                  43
#define EVENT_OBJ_GFX_BEAUTY                      44
#define EVENT_OBJ_GFX_SCIENTIST_1                 45
#define EVENT_OBJ_GFX_LASS                        46
#define EVENT_OBJ_GFX_GENTLEMAN                   47
#define EVENT_OBJ_GFX_SAILOR                      48
#define EVENT_OBJ_GFX_FISHERMAN                   49
#define EVENT_OBJ_GFX_RUNNING_TRIATHLETE_M        50
#define EVENT_OBJ_GFX_RUNNING_TRIATHLETE_F        51
#define EVENT_OBJ_GFX_TUBER_F                     52
#define EVENT_OBJ_GFX_TUBER_M                     53
#define EVENT_OBJ_GFX_HIKER                       54
#define EVENT_OBJ_GFX_CYCLING_TRIATHLETE_M        55
#define EVENT_OBJ_GFX_CYCLING_TRIATHLETE_F        56
#define EVENT_OBJ_GFX_NURSE                       57
#define EVENT_OBJ_GFX_ITEM_BALL                   58
#define EVENT_OBJ_GFX_BERRY_TREE                  59
#define EVENT_OBJ_GFX_BERRY_TREE_EARLY_STAGES     60
#define EVENT_OBJ_GFX_BERRY_TREE_LATE_STAGES      61
#define EVENT_OBJ_GFX_BRENDAN_ACRO_BIKE           62
#define EVENT_OBJ_GFX_PROF_BIRCH                  63
#define EVENT_OBJ_GFX_MAN_4                       64
#define EVENT_OBJ_GFX_MAN_5                       65
#define EVENT_OBJ_GFX_REPORTER_M                  66
#define EVENT_OBJ_GFX_REPORTER_F                  67
#define EVENT_OBJ_GFX_BARD                        68
#define EVENT_OBJ_GFX_ANABEL                      69
#define EVENT_OBJ_GFX_TUCKER                      70
#define EVENT_OBJ_GFX_GRETA                       71
#define EVENT_OBJ_GFX_SPENSER                     72
#define EVENT_OBJ_GFX_NOLAND                      73
#define EVENT_OBJ_GFX_LUCY                        74
#define EVENT_OBJ_GFX_UNUSED_NATU_DOLL            75
#define EVENT_OBJ_GFX_UNUSED_MAGNEMITE_DOLL       76
#define EVENT_OBJ_GFX_UNUSED_SQUIRTLE_DOLL        77
#define EVENT_OBJ_GFX_UNUSED_WOOPER_DOLL          78
#define EVENT_OBJ_GFX_UNUSED_PIKACHU_DOLL         79
#define EVENT_OBJ_GFX_UNUSED_PORYGON2_DOLL        80
#define EVENT_OBJ_GFX_CUTTABLE_TREE               81
#define EVENT_OBJ_GFX_MART_EMPLOYEE               82
#define EVENT_OBJ_GFX_ROOFTOP_SALE_WOMAN          83
#define EVENT_OBJ_GFX_TEALA                       84
#define EVENT_OBJ_GFX_BREAKABLE_ROCK              85
#define EVENT_OBJ_GFX_PUSHABLE_BOULDER            86
#define EVENT_OBJ_GFX_MR_BRINEYS_BOAT             87
#define EVENT_OBJ_GFX_MAY_NORMAL                  88
#define EVENT_OBJ_GFX_MAY_MACH_BIKE               89
#define EVENT_OBJ_GFX_MAY_ACRO_BIKE               90
#define EVENT_OBJ_GFX_MAY_SURFING                 91
#define EVENT_OBJ_GFX_MAY_FIELD_MOVE              92
#define EVENT_OBJ_GFX_TRUCK                       93
#define EVENT_OBJ_GFX_VIGOROTH_CARRYING_BOX       94
#define EVENT_OBJ_GFX_VIGOROTH_FACING_AWAY        95
#define EVENT_OBJ_GFX_BIRCHS_BAG                  96
#define EVENT_OBJ_GFX_ZIGZAGOON_1                 97
#define EVENT_OBJ_GFX_ARTIST                      98
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_NORMAL        99
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_MACH_BIKE    100
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_ACRO_BIKE    101
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_SURFING      102
#define EVENT_OBJ_GFX_RIVAL_BRENDAN_FIELD_MOVE   103
#define EVENT_OBJ_GFX_RIVAL_MAY_NORMAL           104
#define EVENT_OBJ_GFX_RIVAL_MAY_MACH_BIKE        105
#define EVENT_OBJ_GFX_RIVAL_MAY_ACRO_BIKE        106
#define EVENT_OBJ_GFX_RIVAL_MAY_SURFING          107
#define EVENT_OBJ_GFX_RIVAL_MAY_FIELD_MOVE       108
#define EVENT_OBJ_GFX_CAMERAMAN                  109
#define EVENT_OBJ_GFX_BRENDAN_UNDERWATER         110
#define EVENT_OBJ_GFX_MAY_UNDERWATER             111
#define EVENT_OBJ_GFX_MOVING_BOX                 112
#define EVENT_OBJ_GFX_CABLE_CAR                  113
#define EVENT_OBJ_GFX_SCIENTIST_2                114
#define EVENT_OBJ_GFX_DEVON_EMPLOYEE             115
#define EVENT_OBJ_GFX_AQUA_MEMBER_M              116
#define EVENT_OBJ_GFX_AQUA_MEMBER_F              117
#define EVENT_OBJ_GFX_MAGMA_MEMBER_M             118
#define EVENT_OBJ_GFX_MAGMA_MEMBER_F             119
#define EVENT_OBJ_GFX_SIDNEY                     120
#define EVENT_OBJ_GFX_PHOEBE                     121
#define EVENT_OBJ_GFX_GLACIA                     122
#define EVENT_OBJ_GFX_DRAKE                      123
#define EVENT_OBJ_GFX_ROXANNE                    124
#define EVENT_OBJ_GFX_BRAWLY                     125
#define EVENT_OBJ_GFX_WATTSON                    126
#define EVENT_OBJ_GFX_FLANNERY                   127
#define EVENT_OBJ_GFX_NORMAN                     128
#define EVENT_OBJ_GFX_WINONA                     129
#define EVENT_OBJ_GFX_LIZA                       130
#define EVENT_OBJ_GFX_TATE                       131
#define EVENT_OBJ_GFX_WALLACE                    132
#define EVENT_OBJ_GFX_STEVEN                     133
#define EVENT_OBJ_GFX_WALLY                      134
#define EVENT_OBJ_GFX_BRENDAN_FISHING            135
#define EVENT_OBJ_GFX_MAY_FISHING                136
#define EVENT_OBJ_GFX_HOT_SPRINGS_OLD_WOMAN      137
#define EVENT_OBJ_GFX_SS_TIDAL                   138
#define EVENT_OBJ_GFX_SUBMARINE_SHADOW           139
#define EVENT_OBJ_GFX_PICHU_DOLL                 140
#define EVENT_OBJ_GFX_PIKACHU_DOLL               141
#define EVENT_OBJ_GFX_MARILL_DOLL                142
#define EVENT_OBJ_GFX_TOGEPI_DOLL                143
#define EVENT_OBJ_GFX_CYNDAQUIL_DOLL             144
#define EVENT_OBJ_GFX_CHIKORITA_DOLL             145
#define EVENT_OBJ_GFX_TOTODILE_DOLL              146
#define EVENT_OBJ_GFX_JIGGLYPUFF_DOLL            147
#define EVENT_OBJ_GFX_MEOWTH_DOLL                148
#define EVENT_OBJ_GFX_CLEFAIRY_DOLL              149
#define EVENT_OBJ_GFX_DITTO_DOLL                 150
#define EVENT_OBJ_GFX_SMOOCHUM_DOLL              151
#define EVENT_OBJ_GFX_TREECKO_DOLL               152
#define EVENT_OBJ_GFX_TORCHIC_DOLL               153
#define EVENT_OBJ_GFX_MUDKIP_DOLL                154
#define EVENT_OBJ_GFX_DUSKULL_DOLL               155
#define EVENT_OBJ_GFX_WYNAUT_DOLL                156
#define EVENT_OBJ_GFX_BALTOY_DOLL                157
#define EVENT_OBJ_GFX_KECLEON_DOLL               158
#define EVENT_OBJ_GFX_AZURILL_DOLL               159
#define EVENT_OBJ_GFX_SKITTY_DOLL                160
#define EVENT_OBJ_GFX_SWABLU_DOLL                161
#define EVENT_OBJ_GFX_GULPIN_DOLL                162
#define EVENT_OBJ_GFX_LOTAD_DOLL                 163
#define EVENT_OBJ_GFX_SEEDOT_DOLL                164
#define EVENT_OBJ_GFX_PIKA_CUSHION               165
#define EVENT_OBJ_GFX_ROUND_CUSHION              166
#define EVENT_OBJ_GFX_KISS_CUSHION               167
#define EVENT_OBJ_GFX_ZIGZAG_CUSHION             168
#define EVENT_OBJ_GFX_SPIN_CUSHION               169
#define EVENT_OBJ_GFX_DIAMOND_CUSHION            170
#define EVENT_OBJ_GFX_BALL_CUSHION               171
#define EVENT_OBJ_GFX_GRASS_CUSHION              172
#define EVENT_OBJ_GFX_FIRE_CUSHION               173
#define EVENT_OBJ_GFX_WATER_CUSHION              174
#define EVENT_OBJ_GFX_BIG_SNORLAX_DOLL           175
#define EVENT_OBJ_GFX_BIG_RHYDON_DOLL            176
#define EVENT_OBJ_GFX_BIG_LAPRAS_DOLL            177
#define EVENT_OBJ_GFX_BIG_VENUSAUR_DOLL          178
#define EVENT_OBJ_GFX_BIG_CHARIZARD_DOLL         179
#define EVENT_OBJ_GFX_BIG_BLASTOISE_DOLL         180
#define EVENT_OBJ_GFX_BIG_WAILMER_DOLL           181
#define EVENT_OBJ_GFX_BIG_REGIROCK_DOLL          182
#define EVENT_OBJ_GFX_BIG_REGICE_DOLL            183
#define EVENT_OBJ_GFX_BIG_REGISTEEL_DOLL         184
#define EVENT_OBJ_GFX_LATIAS                     185
#define EVENT_OBJ_GFX_LATIOS                     186
#define EVENT_OBJ_GFX_GAMEBOY_KID                187
#define EVENT_OBJ_GFX_CONTEST_JUDGE              188
#define EVENT_OBJ_GFX_BRENDAN_WATERING           189
#define EVENT_OBJ_GFX_MAY_WATERING               190
#define EVENT_OBJ_GFX_BRENDAN_DECORATING         191
#define EVENT_OBJ_GFX_MAY_DECORATING             192
#define EVENT_OBJ_GFX_ARCHIE                     193
#define EVENT_OBJ_GFX_MAXIE                      194
#define EVENT_OBJ_GFX_KYOGRE_1                   195
#define EVENT_OBJ_GFX_GROUDON_1                  196
#define EVENT_OBJ_GFX_FOSSIL                     197
#define EVENT_OBJ_GFX_REGIROCK                   198
#define EVENT_OBJ_GFX_REGICE                     199
#define EVENT_OBJ_GFX_REGISTEEL                  200
#define EVENT_OBJ_GFX_SKITTY                     201
#define EVENT_OBJ_GFX_KECLEON_1                  202
#define EVENT_OBJ_GFX_KYOGRE_2                   203
#define EVENT_OBJ_GFX_GROUDON_2                  204
#define EVENT_OBJ_GFX_RAYQUAZA_2                 205
#define EVENT_OBJ_GFX_ZIGZAGOON_2                206
#define EVENT_OBJ_GFX_PIKACHU                    207
#define EVENT_OBJ_GFX_AZUMARILL                  208
#define EVENT_OBJ_GFX_WINGULL                    209
#define EVENT_OBJ_GFX_KECLEON_2                  210
#define EVENT_OBJ_GFX_TUBER_M_SWIMMING           211
#define EVENT_OBJ_GFX_AZURILL                    212
#define EVENT_OBJ_GFX_MOM                        213
#define EVENT_OBJ_GFX_LINK_BRENDAN               214
#define EVENT_OBJ_GFX_LINK_MAY                   215
#define EVENT_OBJ_GFX_JUAN                       216
#define EVENT_OBJ_GFX_SCOTT                      217
#define EVENT_OBJ_GFX_POOCHYENA                  218
#define EVENT_OBJ_GFX_KYOGRE_3                   219
#define EVENT_OBJ_GFX_GROUDON_3                  220
#define EVENT_OBJ_GFX_MYSTERY_GIFT_MAN           221
#define EVENT_OBJ_GFX_TRICK_HOUSE_STATUE         222
#define EVENT_OBJ_GFX_KIRLIA                     223
#define EVENT_OBJ_GFX_DUSCLOPS                   224
#define EVENT_OBJ_GFX_UNION_ROOM_NURSE           225
#define EVENT_OBJ_GFX_SUDOWOODO                  226
#define EVENT_OBJ_GFX_MEW                        227
#define EVENT_OBJ_GFX_RED                        228
#define EVENT_OBJ_GFX_LEAF                       229
#define EVENT_OBJ_GFX_DEOXYS                     230
#define EVENT_OBJ_GFX_DEOXYS_TRIANGLE            231
#define EVENT_OBJ_GFX_BRANDON                    232
#define EVENT_OBJ_GFX_LINK_RS_BRENDAN            233
#define EVENT_OBJ_GFX_LINK_RS_MAY                234
#define EVENT_OBJ_GFX_LUGIA                      235
#define EVENT_OBJ_GFX_HOOH                       236
#define EVENT_OBJ_GFX_BARD_2                     237

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define EVENT_OBJ_GFX_VAR_0 238
#define EVENT_OBJ_GFX_VAR_1 239
#define EVENT_OBJ_GFX_VAR_2 240
#define EVENT_OBJ_GFX_VAR_3 241
#define EVENT_OBJ_GFX_VAR_4 242
#define EVENT_OBJ_GFX_VAR_5 243
#define EVENT_OBJ_GFX_VAR_6 244
#define EVENT_OBJ_GFX_VAR_7 245
#define EVENT_OBJ_GFX_VAR_8 246
#define EVENT_OBJ_GFX_VAR_9 247
#define EVENT_OBJ_GFX_VAR_A 248
#define EVENT_OBJ_GFX_VAR_B 249
#define EVENT_OBJ_GFX_VAR_C 250
#define EVENT_OBJ_GFX_VAR_D 251
#define EVENT_OBJ_GFX_VAR_E 252
#define EVENT_OBJ_GFX_VAR_F 253

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX EVENT_OBJ_GFX_PICHU_DOLL

#define EVENT_OBJ_ID_PLAYER 0xFF
#define EVENT_OBJ_ID_CAMERA 0x7F

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
